"""empty message

Revision ID: 1_20230609
Revises: 
Create Date: 2023-06-09 19:50:54.759958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1_20230609"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_service_development",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.drop_table("coordinates")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coordinates",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("coordinates", sa.NullType(), nullable=False),
        sa.Column("latitude", mysql.DECIMAL(precision=9, scale=6), nullable=False),
        sa.Column("longitude", mysql.DECIMAL(precision=9, scale=6), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("location_service_development")
    # ### end Alembic commands ###
